// <auto-generated />
namespace Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReturPembayaran : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReturPembayaran));
        
        string IMigrationMetadata.Id
        {
            get { return "201507200656159_ReturPembayaran"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
