// <auto-generated />
namespace Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReturClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReturClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201506241540543_ReturClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
